




















//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//     Author: TECH SOLUTIONS PERU EIRL
//     Developer: Ronald Ibarra
//     Generated at: 04/08/2025 15:51:53
//     All Right reserved
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;

namespace Tsp.Sigescom.Config
{





/// <summary>
///  Grupo de Investigación
/// </summary>
public sealed class LocalResearchGroupSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalResearchGroupSettings(string TenantConnectionString)
        {
//SqlConnection conn = new SqlConnection(TenantConnectionString);
////List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
//string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",1);
//SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
//conn.Open();
//        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
//        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
//        while(parametroConfiguracionLoop)
//        {

//            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
//            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
//        }
//conn.Close();
        }









        /// <summary>
        ///  Grupo de Investigación
        /// </summary>
        //public int ResearchGroupId {
        //    get {
                  
        //       return Convert.ToInt32(parametrosConfiguracion["ResearchGroupId"]);

               
        //    }
        //}

    


}



public partial class SettingsContainer
    {

       
               public  LocalResearchGroupSettings LocalResearchGroupSettings;

                 

        public SettingsContainer(string tenantConnectionString)
        {
             
               //LocalResearchGroupSettings = new  LocalResearchGroupSettings(tenantConnectionString);

     
        SetDictionaries();
        }
   }
}